apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-fabric

resources:
  - namespace.yaml
  - serviceaccounts.yaml

commonLabels:
  app.kubernetes.io/part-of: sentinel-fabric
  app.kubernetes.io/managed-by: kustomize
