apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-sa
  namespace: sentinel-fabric
  labels:
    app.kubernetes.io/name: sentinel
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upstream-stub-sa
  namespace: sentinel-fabric
  labels:
    app.kubernetes.io/name: upstream-stub
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bench-sa
  namespace: sentinel-fabric
  labels:
    app.kubernetes.io/name: bench
    app.kubernetes.io/component: service-account
